apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-java-console-sample
  labels:
    app: es-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-demo
  template:
    metadata:
      labels:
        app: es-demo
    spec:
      volumes:
      - name: es-jks-volume
        secret:
          secretName: demo-es-jks
      containers:
        - name: es-java-sample-producer
          image: cstsui/ibm-kafka-console
          imagePullPolicy: Always
          args: ["$(KAFKA_BOOTSTRAP_SERVERS)", "$(KAFKA_API_KEY)", "-producer", "-topic", "es-mq"]
          envFrom:
          - secretRef:
              name: demo-es-conn-info
          volumeMounts:
          - name: es-jks-volume
            readOnly: true
            mountPath: "/usr/src/app/custom-config/"